export const config = {
  email: "abhi.pandu1296@gmail.com", 
  socials: {
    github: "https://github.com/Abhinav-Viswanathula",
    linkedin: "https://www.linkedin.com/in/abhinav-viswanathula-324350257/",
    instagram: "https://www.instagram.com/abhinav_viswanathula/",
  },

  // ✅ PROJECTS SECTION (12 Projects)
  projects: [
    {
      id: 1,
      title: "AI Cardiologist (ECG)",
      category: "Healthcare / Deep Learning",
      description: "Hybrid CNN-Transformer model for heart condition classification.",
      technologies: "Python, PyTorch, ResNet50V2, Grad-CAM",
      image: "/images/ecg.png", 
      url: "https://drive.google.com/drive/folders/1g4OdMADd9YxK98kGzLusDIp4Ev4BQYaa?usp=drive_link",
    },
    {
      id: 2,
      title: "Pneumonia Detection",
      category: "Medical AI / Computer Vision",
      description: "Deep learning system using CNNs to detect pneumonia in X-rays.",
      technologies: "TensorFlow, Keras, OpenCV, Streamlit",
      image: "/images/pneumonia.png",
      url: "https://drive.google.com/drive/folders/1-8i9siEkUa4HduJZndMOzoO3Y_TF1VEw?usp=drive_link",
    },
    {
      id: 3,
      title: "Brain Tumor Prediction",
      category: "Medical Imaging",
      description: "Diagnostic tool classifying brain tumors from MRI scans.",
      technologies: "Python, TensorFlow, CNN, ResNet",
      image: "/images/brain.png",
      url: "https://drive.google.com/drive/folders/1vIwplrKvpgfx15O4RB3RulDfnKd87EYr?usp=drive_link",
    },
    {
      id: 4,
      title: "RAG Powered Chatbot",
      category: "Generative AI / NLP",
      description: "Context-aware chatbot using RAG for custom document answers.",
      technologies: "Python, LangChain, OpenAI/Ollama, Vector DB",
      image: "/images/rag.png", 
      url: "https://drive.google.com/drive/folders/16msrzP9REVITMLzqDYQa61gshoo2sgIG?usp=drive_link",
    },
    {
      id: 5,
      title: "Fish Image Classification",
      category: "Computer Vision",
      description: "Multi-class image classification model for fish species identification.",
      technologies: "Python, Keras, CNN, Data Augmentation",
      image: "/images/fish.png",
      url: "https://drive.google.com/drive/folders/1kotGPH4iQoqqrabZmCFKaIVQU5WYiDx6?usp=drive_link",
    },
    {
      id: 6,
      title: "Yes Bank Stock Prediction",
      category: "Finance / Time Series",
      description: "Predictive model forecasting Yes Bank's future stock trends.",
      technologies: "Python, Scikit-Learn, Regression, Pandas",
      image: "/images/yes bank.png",
      url: "https://drive.google.com/drive/folders/1JuRvvMC8WAiuQrlw8vzlF_FubSFJ1AST?usp=drive_link",
    },
    {
      id: 7,
      title: "Comments Toxicity Detection",
      category: "NLP / Content Safety",
      description: "NLP model to detect and classify toxic comments on social platforms.",
      technologies: "Python, LSTM/RNN, NLTK, TensorFlow",
      image: "/images/comment.png",
      url: "https://drive.google.com/drive/folders/1oVzy0RiL8ooUfEAgNIc5ULTB0YDBIMjg?usp=drive_link",
    },
    {
      id: 8,
      title: "PhonePe Pulse Analysis",
      category: "Data Visualization / Analytics",
      description: "Geo-spatial analysis of PhonePe transaction data across India.",
      technologies: "Python, Plotly, Streamlit, Pandas, GeoJSON",
      image: "/images/phone_pe.png",
      url: "https://drive.google.com/drive/folders/1mZwSy2tdNOieJU9qHyFA6Jv7JWIiTHmI?usp=drive_link",
    },
    {
      id: 9,
      title: "Shopper Spectrum",
      category: "Unsupervised Learning",
      description: "Customer segmentation system using K-Means clustering.",
      technologies: "Python, Scikit-Learn, K-Means, Matplotlib",
      image: "/images/shopper.png",
      url: "https://drive.google.com/drive/folders/1NXsOMK7HZR_iyqVRdh8hefaw5LfNwQKU?usp=drive_link",
    },
    {
      id: 10,
      title: "Global Vaccination Analysis",
      category: "Data Science / EDA",
      description: "Analysis of global COVID-19 vaccination rates and disparities.",
      technologies: "Python, Pandas, Seaborn, Matplotlib",
      image: "/images/vaccination.png",
      url: "https://drive.google.com/drive/folders/1Sp6AK-plLKTc_WuphUm_64pL8BIcNCrE?usp=drive_link",
    },
    {
      id: 11,
      title: "Food Waste Management",
      category: "Sustainability / Analytics",
      description: "Analytics solution to track and reduce food waste drivers.",
      technologies: "Python, Data Analytics, Optimization Algos",
      image: "/images/food.png",
      url: "https://drive.google.com/drive/folders/1DLICtGq4enUaN_RZGxGqBeAjFalTwkVV?usp=drive_link",
    },
    {
      id: 12,
      title: "Civic Ray",
      category: "Civic Tech / RAG AI",
      description: "AI assistant for municipal governance answering citizen queries.",
      technologies: "Python, LangChain, Ollama, ChromaDB",
      image: "/images/civic_ray.png", 
      url: "https://drive.google.com/drive/folders/1ZMUfnJf6OdVf0h7PUe4rZUhXr_WH_Tiz?usp=drive_link",
    },
  ],

  // ✅ CERTIFICATES SECTION (18 Certificates - Reverse Chronological)
  certificates: [
    {
      id: 1,
      title: "Conflict Management",
      issuer: "Coursera",
      date: "Feb 02, 2026",
      type: "Career Certificate",
      url: "https://coursera.org/share/b4686dbae7891eacac41ea8e2e970018",
    },
    {
      id: 2,
      title: "First Principles of Computer Vision",
      issuer: "Coursera",
      date: "Jan 20, 2026",
      type: "Career Certificate",
      url: "https://coursera.org/share/79470ecdb6b3b22b9f9caf6580e4d3fd",
    },
    {
      id: 3,
      title: "Introduction to Computer Vision and Image Processing",
      issuer: "Coursera",
      date: "Jan 20, 2026",
      type: "Course",
      url: "https://coursera.org/share/160d18588a0b706fdc97e016bdf0c24b",
    },
    {
      id: 4,
      title: "Google Data Analytics",
      issuer: "Google",
      date: "Nov 20, 2025",
      type: "Career Certificate",
      url: "https://coursera.org/share/056577ad596b3e89d507dfaf725f39c2",
    },
    {
      id: 5,
      title: "LangChain for LLM Application Development",
      issuer: "DeepLearning.AI",
      date: "Oct 11, 2025",
      type: "Course",
      url: "https://coursera.org/share/b8474de72d1eaa3d98ba7883165130f7",
    },
    {
      id: 6,
      title: "Machine Learning Specialization",
      issuer: "Stanford University & DeepLearning.AI",
      date: "Feb 12, 2025",
      type: "Career Certificate",
      url: "https://coursera.org/share/8424ed519a6a22c2d4cc30f2426b660c",
    },
    {
      id: 7,
      title: "Building Generative AI-Powered Applications",
      issuer: "Coursera",
      date: "Feb 11, 2025",
      type: "Course",
      url: "https://coursera.org/share/5402e2eeb4229811fae31d95b21545b4",
    },
    {
      id: 8,
      title: "Microsoft AI & ML Engineering",
      issuer: "Microsoft",
      date: "Feb 04, 2025",
      type: "Career Certificate",
      url: "https://coursera.org/share/57706d21ba1934a46912d1f678e510a7",
    },
    {
      id: 9,
      title: "IBM Machine Learning",
      issuer: "IBM",
      date: "Feb 04, 2025",
      type: "Career Certificate",
      url: "https://coursera.org/share/8ccfc9aacb90efdd33d284332f31564c",
    },
    {
      id: 10,
      title: "Generative AI: Elevate your Software Dev Career",
      issuer: "Coursera",
      date: "Feb 03, 2025",
      type: "Course",
      url: "https://coursera.org/share/0328a5f480e2d88a1c5826c0e08f7b96",
    },
    {
      id: 11,
      title: "Generative AI: Prompt Engineering Basics",
      issuer: "Coursera",
      date: "Feb 02, 2025",
      type: "Course",
      url: "https://coursera.org/share/cb7de413ee77a5b55bcd542335f56516",
    },
    {
      id: 12,
      title: "Generative AI: Foundation Models and Platforms",
      issuer: "Coursera",
      date: "Dec 24, 2024",
      type: "Course",
      url: "https://coursera.org/share/193099188b781ddbac89b0a92ca048e7",
    },
    {
      id: 13,
      title: "Generative AI: Introduction and Applications",
      issuer: "Coursera",
      date: "Dec 24, 2024",
      type: "Course",
      url: "https://coursera.org/share/f90f638abf77e682a2e766db60c50c0e",
    },
    {
      id: 14,
      title: "Introduction to Artificial Intelligence (AI)",
      issuer: "Coursera",
      date: "Dec 20, 2024",
      type: "Course",
      url: "https://coursera.org/share/392111ba11f74b5c3b9329eb9cab7f78",
    },
    {
      id: 15,
      title: "Introduction to Git and GitHub",
      issuer: "Google",
      date: "Aug 17, 2024",
      type: "Course",
      url: "https://coursera.org/share/02ce1d314440d1d8f1b2b45518b74e4a",
    },
    {
      id: 16,
      title: "Crash Course on Python",
      issuer: "Google",
      date: "Mar 30, 2024",
      type: "Course",
      url: "https://coursera.org/share/fce24297236e17d124bb38c33a439d7e",
    },
    {
      id: 17,
      title: "Software Development Processes",
      issuer: "University of Minnesota",
      date: "Mar 22, 2024",
      type: "Course",
      url: "https://coursera.org/share/c2bd3614d06756fb3fbd67d043ca52a4",
    },
    {
      id: 18,
      title: "Software Engineering: Implementation and Testing",
      issuer: "University of Minnesota",
      date: "Mar 21, 2024",
      type: "Course",
      url: "https://coursera.org/share/8c071a311f10818da2712e76c62c84ce",
    },
  ],
};